### PR TITLE
add tests

### LINKED ISSUE #23: test: add CLI and client mock test
- serde
  - CLI read-stdin/write-file
  - save the response to local files
  - config
  - serde

### PR DESCRIPTION
**Pull request by tddschn**
refer to #23

### CODE REVIEW

**Review by kemingy — APPROVED** [review]

**Comment by kemingy** [comment]
I think #23 requires much more than this. But it's good to get started.

**Comment by kemingy** [comment]
Seems I cannot dismiss the linked issue.

**Comment by tddschn** [comment]
> I think #23 requires much more than this. But it's good to get started.

Yeah I'm working on more commits. :)

**Comment by tddschn** [comment]
I'm working on monkey patching ModelzClient.inference, will push when it passes tests on my machine.

**Pull request merged**
